<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sebastians-MBP" failures="4" tests="4" name="com.console.RunScript" time="0.110" errors="0" timestamp="25 Feb 2021 07:00:50 GMT" skipped="0">
  <testcase classname="com.console.RunScript" name="runScript" time="0.045">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Register/Script1611241895950.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Register/Script1611241895950.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="com.console.RunScript" name="runScript" time="0.020">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="com.console.RunScript" name="runScript" time="0.019">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="com.console.RunScript" name="runScript" time="0.026">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Login/Script1611188057074.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Desktop/Sebastian-2/NRE/bin/com/console/temp/scripts/Login/Script1611188057074.groovy: 8: unable to resolve class internal.GlobalVariable
 @ line 8, column 1.
   import internal.GlobalVariable
   ^

1 error

	at org.testng.Assert.fail(Assert.java:93)
	at com.console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at com.console.Execute.run(Execute.java:61)
	at com.console.RunConsole.console(RunConsole.java:59)
	at com.console.Main.main(Main.java:85)
]]>
    </failure>
  </testcase> <!-- runScript -->
</testsuite> <!-- com.console.RunScript -->
