<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sebastians-MBP" failures="4" tests="4" name="console.RunScript" time="0.092" errors="0" timestamp="23 Feb 2021 05:34:56 GMT" skipped="0">
  <testcase classname="console.RunScript" name="runScript" time="0.044">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Register/Script1611241895950.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="console.RunScript" name="runScript" time="0.016">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Add Contact_Delete Contact/Script1611247483450.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="console.RunScript" name="runScript" time="0.015">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Verify Existing Contacts/Script1611259297228.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
    </failure>
  </testcase> <!-- runScript -->
  <testcase classname="console.RunScript" name="runScript" time="0.017">
    <failure message="org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 5: unable to resolve class com.kms.katalon.core.testdata.CSVData
 @ line 5, column 1.
   import com.kms.katalon.core.testdata.CSVData
   ^

/Users/sebastiangilarranz/Downloads/Richard-main/temp/scripts/Login/Script1611188057074.groovy: 6: unable to resolve class com.kms.katalon.core.testdata.reader.CSVSeparator
 @ line 6, column 1.
   import com.kms.katalon.core.testdata.reader.CSVSeparator
   ^

2 errors

	at org.testng.Assert.fail(Assert.java:93)
	at console.RunScript.runScript(RunScript.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at console.Execute.run(Execute.java:61)
	at console.RunConsole.main(RunConsole.java:156)
]]>
    </failure>
  </testcase> <!-- runScript -->
</testsuite> <!-- console.RunScript -->
